### ISSUE TITLE
Set filetype by original one

### ISSUE THREAD

**Issue by fecet** [haolian9/nag.nvim#1]
Haven't dig into this plugin yet but how about setting the narrow buffer the same filetype? The current area looks a bit bland.

**Comment by haolian9** [comment]
hi it's intended to not have filetype or syntax set at the time i built this plugin: https://github.com/haolian9/nag.nvim/blob/7b1059002c70f687e7b751754e0548e7e15bd421/lua/nag.lua#L10.

as you can see, this plugin requires haolian9/infra.nvim, which means it's mixed with the whole of my personal nvim runtime, that also makes it hard to be used and contributed by others.
so i wish you can get something useful from it to shape your own one (the impl is very simple IMO), rather than using it directly.

**Comment by fecet** [comment]
Thanks! Actually it can be used out of box like
```
	lazy = true,
	dependencies = {
		"haolian9/infra.nvim",
	},
```
I will investigate it further anyway

**Comment by haolian9** [comment]
good luck!
哈哈，为啥我要这么说？很久之前（大概一年前）我打算实现大部分自己需要的轮子时，我确实打算严格遵循 semver，但在发布几个插件后我发现并没有人会用它们！我也没有需求要在互相依赖的插件间使用版本限制。就先archlinux一样，我最终变成了滚动更新，而且由于插件有点多，改动的更新也会出现不及时的情况。

**Comment by fecet** [comment]
narrow这个功能我觉得可以扩展出不少有趣的用例，希望有更多人可以关注到这个插件

**Comment by haolian9** [comment]
说实话，与其关注这“个”插件，不如关注这“类”插件，尤其是 [NrrwRgn](https://github.com/chrisbra/NrrwRgn) 跟 [yode](https://github.com/hoschi/yode-nvim)
